version: "3.9"

services:
  frontend:
    image: node:18
    volumes:
      - type: bind
        source: ./
        target: /src
    command: >
      sh -c "cd src
             npm i
             chown -R node:node /src/node_modules
             npm run start"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  backend:
    image: internship-registry.zendev.se/coding-stones/coding-stones-backend/staging:latest
    command: >
      sh -c "alembic upgrade head
             uvicorn app.main:app --host 0.0.0.0"

    pull_policy: always
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - backend.env

  database:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - backend.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]

volumes:
  pg-data:
